const nodemailer = require('nodemailer');
const fs = require('fs');


// This is the set-up for nodemailer package
// which is called when "/sendmail" API endpoint is hit.

exports.sendmail = (req,res)=>{
    const userDetails = fs.readFileSync('token.json')
    const keys = JSON.parse(userDetails);
    console.log(keys);

    // Details about the authentication type and
    let transporter = nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 465,
        secure: true,
        auth: {
            type: 'OAuth2',
            clientId: process.env.GOOGLE_CLIENT_ID,
            clientSecret: process.env.GOOGLE_CLIENT_SECRET
        }
    });

    // Details about the mail like To,from,subject etc.
    exports.sendmail = transporter.sendMail({
        from: keys.profile.emails[0].value,
        to: "nadimakhtar97@gmail.com",
        subject: 'Message',
        text: 'This message is auto-generated by emailandoauth20 app.',
        auth: {
            user: keys.profile.emails[0].value,
            refreshToken: keys.refreshToken,
            accessToken: keys.accessToken,
        }
    }).then(()=>{
        res.render('sendmail');
        console.log("email sent successfully");
    });

}
